export const PRODUCTS_SCREEN = 'PRODUCTS_SCREEN';
export const ADD_PRODUCT_SCREEN = 'ADD_PRODUCT_SCREEN';
export const SIGN_UP_SCREEN = 'SIGN_UP_SCREEN';
export const SIGN_IN_SCREEN = 'SIGN_IN_SCREEN';
